export const products = [
  {
    id: 'i1',
    name: 'Sandals',
    description: 'Maroon sandals',
    price: 24.99,
    amount: 1,
    category: 'Shoes',
  },
  {
    id: 'i2',
    name: 'Brogues',
    description: 'Mint green lace up brogues',
    price: 85.99,
    amount: 1,
    category: 'Shoes',
  },
  {
    id: 'i3',
    name: 'Sneakers',
    description: 'Multi-coloured Sneakers',
    price: 69.99,
    amount: 1,
    category: 'Shoes',
  },
  {
    id: 'i4',
    name: 'Handbag',
    description: 'Brown leather handbag',
    price: 89.99,
    amount: 1,
    category: 'Bags',
  },
  {
    id: 'i5',
    name: 'Pouch',
    description: 'Black and white pouch',
    price: 49.99,
    amount: 1,
    category: 'Bags',
  },
  {
    id: 'i6',
    name: 'Wristlet',
    description: 'Brown leather wristlet',
    price: 124.99,
    amount: 1,
    category: 'Bags',
  },
];
